### ISSUE TITLE
您好，没有配置文件config.ini导致错误，能否提供一下这个文件，谢谢您

### ISSUE THREAD

**Issue by felix2chow** [jacky10001/notion2md_to_hugo#4]
Traceback (most recent call last):
  File "/main.py", line 399, in <module>
    main()
  File "/main.py", line 346, in main
    md_store_path_prefix = get_github_action_arg()
  File "/utils.py", line 53, in get_github_action_arg
    cfg["notion"]["token"]
  File "/usr/local/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'notion'

**Comment by jacky10001** [comment]
Hi~ 用記事本建下面的內容並保存成 `config.ini` 即可

```
[notion]
token = YOUR_NOTION_API
database_id = YOUR_NOTION_DATABASE_ID

[img_store]
#local, github
type = local  
path_prefix = content/blogs
url_path_prefix = /blogs
github_token = 
github_repo = 
github_branch = 

[md_store]
path_prefix = content/blogs
```

-----

為方便在本機端測試原作者的程式碼
因此將 [akkuman/akkuman.github.io/.github/workflows/xxx.yml](https://github.com/akkuman/akkuman.github.io/blob/hugo/.github/workflows/notion_to_blog.yml) 裡的參數改到 config.ini 進行測試

-----

以下簡易說明各 section 用法

- [notion] 的部分我引用原作者的說明
  > - notion_token: notion申请的app的api token
  > - notion_database_id: notion中需要作为博客发布的database的id，这是一个uuid，可以通过Share->Copy link获取，注意需要把其中的id转化为uuid的格式，比如 Copy link出来为 https://www.notion.so/akkuman/7bf568e946b946189b2b4af0c61b9e78?v=c45b5e45e96541f4bf81994ab4af1a6e，则notion_database_id为 7bf568e9-46b9-4618-9b2b-4af0c61b9e78，并且你所要发布的文章以及该database都需要invite我们上面申请的app（为了token能够获取到内容）

- [img_store] 的部分目前只有測試本地端儲存 (因為我沒有像原作者用github圖床，近期也沒時間測試 :< )

- [md_store] 的部分就是文章儲存位置

**Comment by jacky10001** [comment]
please refer to file [config.zip](https://github.com/jacky10001/notion2md_to_hugo/files/9896231/config.zip)
